### ISSUE TITLE
Fail to build on macOS 10.15

### ISSUE THREAD

**Issue by ksqsf** [lemire/fastbase64#11]
```
➜  fastbase64 git:(master) ✗ make
cc -fPIC -std=c99 -Wall -Wextra -Wshadow -Wpsabi -Wfatal-errors -O3 -march=native -march=native -mavx2 -c src/chromiumbase64.c -Iinclude
warning: unknown warning option '-Wpsabi' [-Wunknown-warning-option]
1 warning generated.
cc -fPIC -std=c99 -Wall -Wextra -Wshadow -Wpsabi -Wfatal-errors -O3 -march=native -march=native -mavx2 -c src/fastavxbase64.c -Iinclude
warning: unknown warning option '-Wpsabi' [-Wunknown-warning-option]
1 warning generated.
cc -fPIC -std=c99 -Wall -Wextra -Wshadow -Wpsabi -Wfatal-errors -O3 -march=native -march=native -mavx2 -c src/fastavx512bwbase64.c -Iinclude
warning: unknown warning option '-Wpsabi' [-Wunknown-warning-option]
src/fastavx512bwbase64.c:87:23: fatal error: always_inline function
      '_mm512_loadu_si512' requires target feature 'avx512f', but would be
      inlined into function 'fast_avx512bw_base64_encode' that is compiled
      without support for 'avx512f'
        inputvector = _mm512_loadu_si512((__m512i *)(str));
                      ^
1 warning and 1 error generated.
make: *** [fastavx512bwbase64.o] Error 1
```

Not sure if it's a mistake in Makefile. With `make AVX512BW=1` it compiles.

**Comment by ksqsf** [comment]
My bad. This machine doesn't even support AVX512.
